!--------------------------------------------------------- -*- fortran -*- ----
! sample jobcard for proton-induced reactions
! relevant, e.g., for the HADES experiment (strangeness production)
! using relativistic mean-fields (RMF)
!------------------------------------------------------------------------------
! please visit the GiBUU homepage for further information:
! https://gibuu.hepforge.org
! for details please contact:
! * Alexei Larionov
! * Theodoros Gaitanos
!------------------------------------------------------------------------------


! file: code/inputOutput/input.f90
&input
      eventtype       =         300 ! hadron induced
      numEnsembles    =         500
      numTimeSteps    =         300
      delta_T         =         0.2 ! time step size [fm]
      num_runs_SameEnergy=        1 ! number of runs per energy

!      DoPrLevel(1) = .FALSE. ! set this for production runs
!      DoPrLevel(2) = .FALSE. ! set this for production runs

      path_To_Input   = '~/GiBUU/buuinput'
    version = 2023
/

! file: code/init/initHadron.f90
&hadron
      impactParameter = 0.011 ! [fm] (<0: Monte-Carlo choice)
!      bRaiseFlag      = F     ! if true, increase impact parameter b
!      deltaB          = 0.25  ! value to increase b with
!      nRunsPerB       = 1     ! number of runs per b value
!      perturbative    = F     ! is projectile a perturbative particle?
      numberParticles =   200 ! #projectiles per ensemble
      particleId      =     1 ! projectile: id
      antiParticle    = F     ! projectile: antiparticle flag
      particleCharge  =     1 ! projectile: charge
      ekin_lab        =  3.50 ! projectile: kinetic energy [GeV]
      E_bind          =     0 ! binding energy [GeV]
      iniType         =     2 ! 0: default, 1: p&x gaussian, 2: x gaussian
      zChoice         =     2 ! 1: distance form surface, 2: fixed z
!      delta           = 0.500 ! distance [fm] (see code doku)
!      deltaZ          = 5.00  ! distance [fm] (see code doku)
      width           =  0.80 ! Width of a gaussian density profile [fm].
!      debug           = F     ! additional debug output
 /


! file: code/density/nucleus.f90
&target
!      fermiMotion = .FALSE.
!      Z=  1, A=  1 ! proton,neutron, deuterium
!      Z=  4, A=  9, densitySwitch_Static=4 ! Be
!      Z=  6, A= 12, densitySwitch_Static=4 ! C
!      Z=  6, A= 12 ! C
!      Z=  7, A= 14 ! N
!      Z= 10, A= 20 ! Ne
!      Z= 16, A= 32 ! S
!      Z= 20, A= 40 ! Ca
!      Z= 26, A= 56 ! Fe
!      Z= 29, A= 64 ! Cu
!      Z= 36, A= 84 ! Kr
      Z= 41, A= 93, densitySwitch_Static=8 ! Nb
!      Z= 54, A=131 ! Xe
!      Z= 82, A=208 ! Pb
/


! file: code/density/density.f90
&initDensity
      linearInterpolation = F
      gridSize            = 15.0, 15.0, 20.0
      gridPoints          = 20,   20,   25
/

! file: code/rmf/RMF.f90
&RMF_input
      RMF_flag        = T
      grad_flag       = T
      kaonpot_flag    = T
      N_set           = 2
      fact_pbar       =  0.220000
      fact_hyp        =  0.666666
      fact_antihyp    =  1.000000
      fact_Xi         =  0.333333
      fact_antiXi     =  1.000000
      fact_kaon       =  0.333333
/

! file: code/collisions/collisionTerm.f90
&collisionterm
      threeBodyProcesses = F
      energyCheck        =  0.100
      maxOut             =     30
/

! file: code/collisions/phaseSpace/winkelVerteilung.f90
&angular_distribution
      deltaPWave              = F
      rho_pipi_nonIsotropic   = F
      pionNucleon_backward    = F
/


&initRandom
  Seed = 45678,   ! seed for the random number
/
