!--------------------------------------------------------- -*- fortran -*- ----
! sample jobcard for proton-induced reactions using REAL particles
!------------------------------------------------------------------------------
! please visit the GiBUU homepage for further information:
! https://gibuu.hepforge.org
! for details please contact:
! * Alexei.Larionov@theo.physik.uni-giessen.de
! * Theodoros.Gaitanos@theo.physik.uni-giessen.de
!------------------------------------------------------------------------------

! file: code/inputOutput/input.f90
&input
      eventtype       =         300 ! hadron induced
      numEnsembles    =         200
      numTimeSteps    =         100
      delta_T         =        0.50
      num_runs_SameEnergy=        1 ! number of runs per energy

!      DoPrLevel(1) = .FALSE. ! set this for production runs
!      DoPrLevel(2) = .FALSE. ! set this for production runs

      path_To_Input   = '~/GiBUU/buuinput'
    version = 2023
/


! file: code/init/initHadron.f90
&hadron
      impactParameter =   -15. ! [fm] (<0: Monte-Carlo choice)
!      bRaiseFlag      = F     ! if true, increase impact parameter b
!      deltaB          = 0.25  ! value to increase b with
!      nRunsPerB       = 1     ! number of runs per b value
!      perturbative    = F     ! is projectile a perturbative particle?
!      numberParticles =   200 ! #projectiles per ensemble
      particleId      =     1 ! projectile: id
      antiParticle    = F     ! projectile: antiparticle flag
      particleCharge  =     1 ! projectile: charge
      ekin_lab        =  1.00 ! projectile: kinetic energy [GeV]
!      E_bind          =     0 ! binding energy [GeV]
!      iniType         =     0 ! 0: default, 1: p&x gaussian, 2: x gaussian
!      zChoice         =     1 ! 1: distance form surface, 2: fixed z
!      delta           = 0.500 ! distance [fm] (see code doku)
!      deltaZ          = 5.00  ! distance [fm] (see code doku)
!      width           =  1.00 ! Width of a gaussian density profile [fm].
!      debug           = F     ! additional debug output
 /

! file: code/density/nucleus.f90
&target
!      fermiMotion = .FALSE.
!      Z=  1, A=  1 ! proton,neutron, deuterium
!      Z=  4, A=  9, densitySwitch_Static=4 ! Be
!      Z=  6, A= 12, densitySwitch_Static=4 ! C
!      Z=  6, A= 12 ! C
!      Z=  7, A= 14 ! N
      Z= 10, A= 20 ! Ne
!      Z= 16, A= 32 ! S
!      Z= 20, A= 40 ! Ca
!      Z= 26, A= 56 ! Fe
!      Z= 29, A= 64 ! Cu
!      Z= 36, A= 84 ! Kr
!      Z= 41, A= 93, densitySwitch_Static=8 ! Nb
!      Z= 54, A=131 ! Xe
!      Z= 82, A=208 ! Pb
/

! file: code/database/particleProperties.f90
&initDatabase
      propagationSwitch = 0 ! 0=all resonances with more than 1 star
/

! file: code/numerics/random.f90
&initRandom
      SEED=11111                ! Seed for the random number
/

! file: code/rmf/RMF.f90
&RMF_input
      RMF_flag        = T
      grad_flag       = T
      N_set           = 2
      fact_pbar       =  0.220000
      fact_hyp        =  0.666666
      fact_antihyp    =  0.666666
      fact_Xi         =  0.333333
      fact_antiXi     =  0.333333
      fact_kaon       =  0.333333
/

! file: code/density/density.f90
&initDensity
      linearInterpolation = F
      gridSize            = 15.0, 15.0, 15.0
      gridPoints          = 15,   15,   15
/


! file: code/potential/coulomb/coulomb.f90
 &coulomb
      coulombFlag     = T
/

! file: code/collisions/collisionTerm.f90
&collisionterm
      threeBodyProcesses = F
      energyCheck        =  0.100
      maxOut             =     20
/

! file: code/collisions/phaseSpace/winkelVerteilung.f90
&angular_distribution
      deltaPWave              = F
      rho_pipi_nonIsotropic   = F
      pionNucleon_backward    = F
/
