SUBDIREXCL :=
FILEEXCL := test.f90 testH2DBspline.f90 rebinHistMC.f90 sumHist.f90 sumHistMC.f90 sumHistMC_avg.f90 smearHistMC.f90 smearHist.f90 integrateHist.f90 writeHist2Dintegrals.f90 mixHist.f90 Read_Varirates.f90
EXEFILE := BinSumHistMC.f90 BinSumHistMC_avg.f90 BinSumHistMP.f90 BinSumHist2D.f90 Read_Varirates.f90